### ISSUE TITLE
What is the use case of ComfyScript?

### ISSUE THREAD

**Issue by spinagon** [Chaoses-Ib/ComfyScript#1]
Can it be directly executed, or transformed back into a graph?

**Comment by Chaoses-Ib** [comment]
See https://github.com/comfyanonymous/ComfyUI/issues/612#issuecomment-1747325863. The two use cases you mentioned are both possible. But they are not yet implemented.

**Comment by Chaoses-Ib** [comment]
The two features are both implemented now. See readme for details.
