### ISSUE TITLE
Custom node that fail to load can make the whole loading fail

### ISSUE THREAD

**Issue by ShagaONhan** [Chaoses-Ib/ComfyScript#13]
I found this node make the whole load to fail:
IFRNet VFI
It's from ComfyUI-Frame-Interpolation

I added and exception catch to ignore it in nodes.py and the rest of the nodes loaded properly
![image](https://github.com/Chaoses-Ib/ComfyScript/assets/158047700/78b9b9d7-5f5b-4291-83cd-f110a1c06156)

Edit:
The same thing happens in the nodes.py of the real mode.

**Comment by Chaoses-Ib** [comment]
Fixed. Use `git pull` to update.
