### ISSUE TITLE
Import main fail in real mode

### ISSUE THREAD

**Issue by ShagaONhan** [Chaoses-Ib/ComfyScript#14]
![image](https://github.com/Chaoses-Ib/ComfyScript/assets/158047700/006761de-3ae8-48a0-9551-52607c1a8da4)

In my case the value of __file__ is:
'C:\\work\\misc_rep\\python\\ComfyUI\\custom_nodes\\ComfyScript\\src\\comfy_script\\runtime\\real\\__init__.py'

And the value of comfy_ui is WindowsPath('C:/work/misc_rep/python/ComfyUI/custom_nodes')
It should be C:/work/misc_rep/python/ComfyUI/

I replaced with comfy_ui = Path(__file__).resolve().parents[6] and it worked

**Comment by Chaoses-Ib** [comment]
Fixed. I forgot to test the real mode after changing the project layout...
