### ISSUE TITLE
How to load a comfyui server with basic auth?

### ISSUE THREAD

**Issue by jervenclark** [Chaoses-Ib/ComfyScript#32]
Is there any way to load a comfyui server that has basic authentication?

**Comment by Chaoses-Ib** [comment]
As far as I know, the official ComfyUI server doesn't have any auth mechanism. Can you give an example of the basic auth you mentioned?

**Comment by jervenclark** [comment]
Thanks for the response and I'm sorry for being unclear. This is the [basic auth](https://en.wikipedia.org/wiki/Basic_access_authentication) that I mean not the one implemented by comfy UI. 
Is there a way to pass headers when loading the comfy server? Maybe something similar to this?
```
load(https://localhost:8188, headers={'Authorization': 'Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=='})
```

**Comment by Chaoses-Ib** [comment]
v0.4.4 is released. Now you can do it like this:
```python
load(Client('http://127.0.0.1:8188/', session_factory=lambda: aiohttp.ClientSession(
    auth=aiohttp.BasicAuth('Aladdin', 'open sesame')
    # auth=aiohttp.BasicAuth.decode('Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==')
    # headers={'Authorization': 'Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=='}
)))
```
See [`ClientSession`](https://docs.aiohttp.org/en/latest/client_reference.html#aiohttp.ClientSession) for more options.

**Comment by jervenclark** [comment]
Thank you! I will try this one.
