### ISSUE TITLE
I have installed the ComfyUI_Ib_CustomNodes Package. But can't seem to use the ImageToPIL Node

### ISSUE THREAD

**Issue by AdonisCodes** [Chaoses-Ib/ComfyScript#39]
I have done the following steps:
<img width="1107" alt="Untitled 2" src="https://github.com/Chaoses-Ib/ComfyScript/assets/122154257/510ed23f-bff0-46fe-aadb-44410db51cfc">
<img width="584" alt="Untitled 3" src="https://github.com/Chaoses-Ib/ComfyScript/assets/122154257/dc4b864f-cda2-4d3b-8635-25cdd903e9ba">

**Comment by Chaoses-Ib** [comment]
Are you using the official ComfyUI or the comfyui package? If it's the former, is ComfyScript installed under `ComfyUI/custom_nodes`?

**Comment by AdonisCodes** [comment]
Sorry for the long response.
I currently opted in exporting the json workflows, as they actually work better for my usecase (Might change later)

Thanks for the help!
I installed it via the official documentation by cloning the ComfyUI repo
