### ISSUE TITLE
See multiple images, but without multiple samplers

### ISSUE THREAD

**Issue by ghostsquad** [Chaoses-Ib/ComfyScript#54]
I have a workflow that makes several changes to an image, but not through a sampler (each time). Is there a way to see those images next to each other like this:

![plot](https://github.com/Chaoses-Ib/ComfyScript/assets/903488/da882200-8385-49d7-93ac-ccdd268e6506)

I tried to add `PreviewImage` but I get some weird output:

```
HBox(children=(HTML(value='<style>\n.cell-output-ipywidget-background {\nbackground-color: transparent !import…
```

**Comment by Chaoses-Ib** [comment]
Looks like your notebook uses the wrong mimetype. Choosing `application/...` should fix it.

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/50246090/3503fa2e-8ac9-4426-8e0c-a39030fa65c1)

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/50246090/60b5b995-033a-459e-b9e6-c1b08cfc4b44)

**Comment by ghostsquad** [comment]
hmmm, I don't have that option.

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/903488/1e8c14de-ec77-431a-83e8-b6af55569450)

**Comment by ghostsquad** [comment]
looks like sometimes there are multiple outputs shown.. in the case below, the second output is set to the presentation mode you linked to. But when there's just an image (only one output node below the python code), there's presentation modes listed above are what I see.

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/903488/5b92d4dd-7ca7-4e18-a4f8-77c34ce882af)

**Comment by Chaoses-Ib** [comment]
If there is only one output image, it will be displayed as an image directly without any widgets. Could you reproduce `HBox(children=` and choose the mimetype from the output cell displaying it?

**Comment by ghostsquad** [comment]
Problem fixed by restarting VSCode. I think at one point while I was trying things out, I changed the presentation mode, then somehow could find out how to change it back. Now it's back to the one you mentioned, and `PreviewImage` is working alongside the sampler image too. 🎉
