### ISSUE TITLE
transpiler reusing variables that should be unique

### ISSUE THREAD

**Issue by nykwil** [Chaoses-Ib/ComfyScript#55]
I have a custom node that takes json text and then outputs a whole bunch of different prompts for different purposes, scene, detailer, upscale, etc. the transpiler however uses the same variable for each of the outputs of the node:

Transpiler generates this:
string, string, _, _, _, _, string, string = PromptBuilder(string, 1910, 'realistic photo', 'hallway', 'woman', 'Lisa', '', 'lab coat', 'standing', 'looking down', 'tiled floor, mri machine', '', 'long shot, wide angle', '4K', '', '', 'glasses, gloves, carpet')

but each of those "string" is used in a different ksampler.

**Comment by Chaoses-Ib** [comment]
Could you share the workflow?

**Comment by nykwil** [comment]
![image](https://github.com/Chaoses-Ib/ComfyScript/assets/1003128/21625767-c13b-4bbe-8349-e17e092ef84f)
[_simple_pdb.json](https://github.com/user-attachments/files/15909157/_simple_pdb.json)

becomes:
image, _, positive, _, _, _, _, _, _, _, filename, _ = SDPromptReader('ComfyUIxxy_00002_.png', 0)
positive, positive, positive, positive, _, _, positive, positive = PromptBuilder(positive, 1529, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '')
# _, _, _ = SDPromptSaver(image, filename, positive, r'New\Deliberate_v4.safetensors', 'clearvae_main.safetensors', 756313888080631, 20, 8, 'euler', 'normal', None, 1, 1, positive, '', 'png', True, True, True, 100, '%Y-%m-%d', '%H%M%S', False, '')

**Comment by Chaoses-Ib** [comment]
Sorry for this late reply. Another one reported a similar bug with `SplitSigmasDenoise` today. It's now fixed. I can't find the `Prompt Builder` in your workflow to test, but they are very likely to be the same issue. Feel free to reopen this issue if it's still not fixed.
