### ISSUE TITLE
How to use it? This plugin is not show up in chrome.Is it the code editor as front replace web browser for comfyui?

### ISSUE THREAD

**Issue by Erwin11** [Chaoses-Ib/ComfyScript#57]
Sorry, I'm noob. I dont know python , but I can learn. I couldn't find example caes.
How to use it? I know this is translate .json file to code mode. 
But, where is this tool? How cloud I found it?
For example, I have text to image workflow.  How can I edit it in code mode with comfyui backend in realtime?
in example / runtime.ipynb, I open it in vscode, 
vscode tell me to create server or use python venv, Can I use comfyui venv : ComfyUI_windows_portable  folder ? 
What is the connectiion with this plugin ?
It seems not for animator , designer,  I know it is use code to control workflow, but ,where is this tool so I can type the code.

**Comment by Chaoses-Ib** [comment]
> But, where is this tool? How cloud I found it?

It's designed to be used in Jupyter Notebook, i.e. `.ipynb` files, so you can preview the images in the notebook. But it's also supported to just run `.py` files.

> vscode tell me to create server or use python venv, Can I use comfyui venv : ComfyUI_windows_portable folder ?

Yes.

> What is the connectiion with this plugin ?

After you opened the notebook and selected the venv, running the cells will execute the coded workflow.

> It seems not for animator , designer, I know it is use code to control workflow, but ,where is this tool so I can type the code.

That's true. It'll a bit hard to use if one doesn't have Python experience.

**Comment by Erwin11** [comment]
I add comfyui ComfyUI_windows_portable  venv now, then run it, gets this error: 
![image](https://github.com/Chaoses-Ib/ComfyScript/assets/6300501/f908e4af-8f94-4f94-9604-0102a37f86df)

[comfyui.log](https://github.com/user-attachments/files/15925687/comfyui.log)
[comfyui.prev.log](https://github.com/user-attachments/files/15925692/comfyui.prev.log)
[comfyui.prev2.log](https://github.com/user-attachments/files/15925695/comfyui.prev2.log)

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/6300501/caa01ffa-dc96-4da6-b6fd-a9b7acdf0040)
I had installed by [ pip install "comfy-script[default,solara]" ]
What I miss？

**Comment by Erwin11** [comment]
developing a workflow with it. Is it needs Transpiler workflow.json every time  after I changed it by using web brower?
Is is possible? for example: web browser edit workflow, save as json file. sync it in ipynb .
I found it run comfyui in vscode, I can't use in web brower at same time.
what if I want to CI/CD this json file by using web browser to desgin node pipeline & create function ,variable (maybe,I'm not so sure ) .  Some thing like low code, Visual development for front developers. Maybe I'm misunderstand it.
The reason why I'm use it is may some time I need save function ,save the value of first pipeline , then reuse it Or use it to the next time .

**Comment by Erwin11** [comment]
what have I done:
I'm using ComfyUI_windows_portable,  hash : a82fae2
install custom_nodes\ComfyScript, hash : fed6d97
put custom_nodes\ComfyScript\pyproject.toml  to ComfyUI_windows_portable\python_embeded
in python_embeded folder , cmd , python -m pip install "comfy-script[default,solara]"
open ComfyScript folder/example/, copy runtime.ipynb in demo folder, use vscode to open it, connect with python_embeded venv,
then click run button.

**Comment by Chaoses-Ib** [comment]
> run it, gets this error:

There is a collision. Possibly you have a custom node named `Path` or a node outputs `Path`, and it overwrote `pathlib.Path` used by the runtime. I'll fix it later.

> developing a workflow with it. Is it needs Transpiler workflow.json every time after I changed it by using web browser?
> Is is possible? for example: web browser edit workflow, save as json file. sync it in ipynb .

Not possible currently. But why don't you just modify the code?

> I found it run comfyui in vscode, I can't use in web brower at same time.

If your ComfyUI isn't running on the default port (8188), you need to specify it in `load`, e.g. `load('http://127.0.0.1:8189/')`.

另外，如果对英语不太熟的话可以用中文，这样更好理解些。

**Comment by Chaoses-Ib** [comment]
> put custom_nodes\ComfyScript\pyproject.toml to ComfyUI_windows_portable\python_embeded
> in python_embeded folder , cmd , python -m pip install "comfy-script[default,solara]"

You shouldn't install it this way. This is installing from PyPI, not from `custom_nodes`. The correct way is to run `python -m pip install -e ".[default,solara]"` under `custom_nodes\ComfyScript`.

The bug you reported is fixed. You can run `git pull` to update after reinstalling it in the right way.

**Comment by Erwin11** [comment]
原来是国人大佬啊啊啊~ 5555 原谅我可怜的英语

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/6300501/35ce75fc-e7d8-47c6-a193-acad5b23226c)
我按您上面的 python -m pip install -e ".[default,solara]" under custom_nodes\ComfyScript. 试了， 还是启动不了。

这个是日志
[comfyui.log](https://github.com/user-attachments/files/15928384/comfyui.log)

这个插件是不是很多第三方的插件会不支持啊 ？比如这种
![image](https://github.com/Chaoses-Ib/ComfyScript/assets/6300501/07ddce46-1cbe-43db-b553-69f1ed3ca3db)

**Comment by Chaoses-Ib** [comment]
要在 `custom_nodes\ComfyScript` 里运行 `git pull` 更新下。

> 这个插件是不是很多第三方的插件会不支持啊 ？比如这种

那些错误提示只是没法生成参数类型，手动填参数还是能用的，比如 VHS 的用法可以参考这里：https://github.com/Chaoses-Ib/ComfyScript/issues/22#issuecomment-1937053248

**Comment by Erwin11** [comment]
是更新过的，还是这样。 算了。
