### ISSUE TITLE
How can I create a Flask app that runs ComfyScript code?

### ISSUE THREAD

**Issue by pranaykoppula** [Chaoses-Ib/ComfyScript#64]
For the life of me, I can't get this to work:

```
from flask import Flask, request, Response, jsonify

app = Flask(__name__)
from comfy_script.runtime import *
load(args=ComfyUIArgs('--force-fp16'))
from comfy_script.runtime.nodes import *

def comfy_function(prompt:str):
    with Workflow():
[. Some ComfyScript code ...]

@app.route("/generate",methods=['POST'])
def genimages()
    data = request.get_json()
    usr_prompt=data.get('prompt')
    res=comfy_function(usr_prompt)
    response = jsonify(res)
    return response

if __name__ == "__main__":
    app.run(host = 'X.X.X.X', port= XXXX)

```

I don't know what I'm doing wrong. Comfy seems to start, but when I send a request to the API, nothing happens. Is this simply not possible?

**Comment by Chaoses-Ib** [comment]
How do you wait for the workflow and get the results in `[. Some ComfyScript code ...]`?

**Comment by pranaykoppula** [comment]
I thought that could work synchronously. I mean even if that is the issue, when I try to print something before I call the comfy_function, it doesn't print anything. But the comfy server seems to start

**Comment by pranaykoppula** [comment]
I think something about the comfy server starting up prevents the flask app from working

**Comment by Chaoses-Ib** [comment]
Does connecting to a separate ComfyUI server work, e.g. `load('http://127.0.0.1:8188/')`?

If it does, you can try to disable the in-process ComfyUI server by:
```python
from comfy_script.runtime.real import *
load(args=ComfyUIArgs('--force-fp16'), no_server=True)
from comfy_script.runtime.real.nodes import *
```

**Comment by Chaoses-Ib** [comment]
> I modified the load image and save image nodes to accept and return variables, and this function works as expected in jupyter notebook when I use real mode

Virtual mode differs from real mode in several ways. You can't just read `['ui']` and get the images. Instead, do this:
```python
from PIL import Image

image = EmptyImage(512, 512, 1)
image = PreviewImage(image)

image_batch = image.wait()

# Get the first image
image: Image.Image = image_batch[0]

# Get all images in the batch
images: list[Image.Image] = image_batch.wait()
```
Or with `await`:
```python
from PIL import Image

image = EmptyImage(512, 512, 1)
image = PreviewImage(image)

image_batch = await image

# Get the first image
image: Image.Image = await image_batch.get(0)

# Get all images in the batch
images: list[Image.Image] = await image_batch
```

**Comment by pranaykoppula** [comment]
I was able to make this work in a Jupyter notebook. The issue now seems to be that after the Comfy server starts, I'm not able to send anything to the Flask endpoint.

**Comment by pranaykoppula** [comment]
I just wanna know how to use ComfyScript inside of a flask app

**Comment by Chaoses-Ib** [comment]
It works fine on my side:

![image](https://github.com/user-attachments/assets/ca750d97-803f-4158-9865-ae200b75afec)

```python
from flask import Flask, request, Response, jsonify

app = Flask(__name__)
from comfy_script.runtime import *
load(args=ComfyUIArgs('--force-fp16'))
from comfy_script.runtime.nodes import *

def comfy_function(prompt:str):
    print('Prompt:', prompt)
    with Workflow():
        image = EmptyImage(512, 512, 1)
        image = PreviewImage(image)

        image_batch = image.wait()
        # Get the first image
        image: Image.Image = image_batch[0]
        # TypeError: Object of type PngImageFile is not JSON serializable
        # return image
        return 'abcd'

@app.route("/generate",methods=['POST'])
def genimages():
    data = request.get_json()
    usr_prompt=data.get('prompt')
    res=comfy_function(usr_prompt)
    response = jsonify(res)
    return response

if __name__ == "__main__":
    app.run(host ='127.0.0.1', port= 11007)
```

**Comment by pranaykoppula** [comment]
![image](https://github.com/user-attachments/assets/689547e6-f9ec-4104-a1c1-dac79d26ca70)

It's just crickets over here for me.

Very kind you to test it yourself. Thank you.

**Comment by Chaoses-Ib** [comment]
What's your ComfyUI and ComfyScript version? I tested with the newest version, ComfyUI 
 https://github.com/comfyanonymous/ComfyUI/commit/48eb1399c02bdae7e14b2208c448b69b382d0090 and ComfyScript 167cbd231f9e4b4477fe207d169c4502fba3aca7. The Flask version is 3.0.3 and the Python version is 3.10.10. On Windows 11.

Custom nodes may also cause issues. You can temply disable them by:
```python
load(args=ComfyUIArgs('--disable-all-custom-nodes', '--force-fp16'))
```

**Comment by pranaykoppula** [comment]
I installed ComfyUI on a new system yesterday, and installed ComfyScript right after. I'm using Python 3.10 too and I'm using Ubuntu. Unfortunately I do need the custom nodes.

My Flask code looks pretty much identical to yours but I suspect I've made a monumentally stupid mistake somewhere and it probably has nothing to do with ComfyScript.

Thank you for going so far out of your way to help me. I'll edit this post if I'm able to fix it.

**Comment by pranaykoppula** [comment]
Well, I seem to be able to queue prompts now, which is a step in the right direction. 
I tried editing the save_images function in the SaveImage node to make it return an PIL Image

I'm getting this error now:
<comfy_script.runtime.data.NodeOutput object at 0x7fd2cda991b0>
'NodeOutput' object is not subscriptable

**Comment by pranaykoppula** [comment]
Okay, I honestly don't know what I did right, but I made it work.

Thank you, @Chaoses-Ib  for making arguably the most useful ComfyUI extension and for being so helpful.
