### ISSUE TITLE
Loading lora -> error

### ISSUE THREAD

**Issue by lschaupp** [Chaoses-Ib/ComfyScript#66]
model, clip = LoraLoader(self.model, self.clip, lora_weights, 1, 1)

-> getting NoneType as an error when it tries to load the lora checkpoint

Anyone knows why?

**Comment by Chaoses-Ib** [comment]
```python
print(type(self.model), type(self.clip), type(lora_weights))
```
Is any of these None?

**Comment by lschaupp** [comment]
I have confirmed that all of these are not NoneType - hence raising the issue.
Also without the line of code, the rest of my pipeline works where self.model and self.clip is being used of course.

**Comment by Chaoses-Ib** [comment]
Are you using virtual mode or real mode? Can you share the original log of ComfyScript and ComfyUI?

**Comment by Chaoses-Ib** [comment]
Close because the issue can't be reproduced. Feel free to reopen it if you have further information.
