### ISSUE TITLE
Can't import plugin ,Error is: module 'ComfyScript.nodes.ComfyUI_Ib_CustomNodes' has no attribute 'NODE_CLASS_MAPPINGS'

### ISSUE THREAD

**Issue by Erwin11** [Chaoses-Ib/ComfyScript#7]
Installed the lastest version. had installed requirements.txt
Error Info:
```
ComfyScript: Loading nodes...
Traceback (most recent call last):
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyScript\__init__.py", line 20, in <module>
    NODE_CLASS_MAPPINGS.update(ComfyUI_Ib_CustomNodes.NODE_CLASS_MAPPINGS)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ComfyScript.nodes.ComfyUI_Ib_CustomNodes' has no attribute 'NODE_CLASS_MAPPINGS'

Cannot import E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyScript module for custom nodes: module 'ComfyScript.nodes.ComfyUI_Ib_CustomNodes' has no attribute 'NODE_CLASS_MAPPINGS'
Adding E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
```
![160413](https://github.com/Chaoses-Ib/ComfyScript/assets/6300501/b9b678a6-379e-487f-af2f-534e75c553e7)

**Comment by Chaoses-Ib** [comment]
Looks like you failed to clone the git submodule due to some reason.You can try to run this:
```
git -C "E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyScript" submodule update --init --recursive
```
If this doesn't work, just delete directories under `E:\AI\ComfyUI\ComfyUI-webui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyScript\nodes`.

**Comment by Erwin11** [comment]
It works.  My bad,how to install,  I didn't see that very clearly

**Comment by Chaoses-Ib** [comment]
The [installation section](https://github.com/Chaoses-Ib/ComfyScript#installation) has given the command lines:
```sh
cd ComfyUI/custom_nodes
git clone --recurse-submodules https://github.com/Chaoses-Ib/ComfyScript.git
cd ComfyScript
python -m pip install -r requirements.txt
```
You may forgot `--recurse-submodules` when cloning the repo.

I'll add this to ComfyUI Manager to make the installation easier after some features are finished.

**Comment by Chaoses-Ib** [comment]
Now one should see this error message if the submodule is empty:

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/50246090/fa15754e-1f7a-420b-be51-28c10f2624db)

**Comment by Erwin11** [comment]
yes ，I forgot to typing --recurse-submodules. Follow the readme.md, installation is OK.

**Comment by Chaoses-Ib** [comment]
Now nodes are installed as package dependencies instead of Git submodules. `pip install -e .` or `pip install -r requirements.txt` will install them. `--recurse-submodules` is no longer needed.
