### ISSUE TITLE
ComfyScript: Invalid config

### ISSUE THREAD

**Issue by cihangoksu** [Chaoses-Ib/ComfyScript#79]
Is this a warning or an important error I need to handle? For a simple workflow it didn't cause any problem. Is there a way to debug it origin, any help please? Thank you!

![image](https://github.com/user-attachments/assets/e9e42707-82ff-4884-8f81-4b88cc861189)

**Comment by Chaoses-Ib** [comment]
It's the node Scribble_PiDiNet_Preprocessor has some unusual config and can't be parsed by ComfyScript. It will not be avaliable in ComfyScript but other nodes should work fine.

**Comment by Chaoses-Ib** [comment]
So the node's config is wrong, even ComfyUI can't recognize it correctly. I've made a PR to fix it: https://github.com/Fannovel16/comfyui_controlnet_aux/pull/477

**Comment by Chaoses-Ib** [comment]
Now my fix PR has been merged. You can update comfyui_controlnet_aux to solve this issue.
