### ISSUE TITLE
CheckpointSave doesnt't seem to work

### ISSUE THREAD

**Issue by JTriggerFish** [Chaoses-Ib/ComfyScript#82]
I am not sure what is the root cause of the issue but CheckPointSave doesn't seem to be doing anything even though it does work in the ComfyUI UI.
It just seems to be alltogether ignored, with no error message.

**Comment by Chaoses-Ib** [comment]
Can't reproduce. Are you using `with Workflow()` or `CheckpointSave(...).wait()`?

![image](https://github.com/user-attachments/assets/37700898-945f-4736-b0f6-a252e46d7cd9)

**Comment by JTriggerFish** [comment]
Ahh - makes sense, you're right, my function was outside of with workflow() and I didn't have the wait().
Thank you so much for the very quick response.
And thank you for the amazing work, the backend of comfyui is great but I find node workflows very unproductive, this is really brillant work.
