### ISSUE TITLE
PIL to Image/Mask broken

### ISSUE THREAD

**Issue by mcmanusef** [Chaoses-Ib/ComfyScript#83]
In the definition of the actions for the PIL to Image nodes, the self is missing, causing them to be unusable

Currently it is
def pil_images_to_masks(images: Iterable[Image.Image]) -> torch.Tensor:

It should be 
def pil_images_to_masks(self, images: Iterable[Image.Image]) -> torch.Tensor:

(in image.py)

**Comment by Chaoses-Ib** [comment]
Thanks for your report. It should be fixed now. You can run `pip install ComfyUI_Ib_CustomNodes>=0.2.3` to update.
